index:
  slogan:
    enable: true
    text: 華爾街沒有新鮮事

navbar:
  blog_title: BenJi
  favicon: /img/favicon.ico

about:
  avatar: /img/favicon.ico
  name: "Ben"
  intro: "A trader and investor"

favicon: /img/favicon.ico

footer:
  content: ""