index:
  slogan:
    enable: true
    text: 華爾街沒有新鮮事

navbar:
  blog_title: BenJi
  favicon: /img/favicon.ico
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    # - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

about:
  avatar: /img/favicon.ico
  name: "Ben"
  intro: "A trader and investor"

favicon: /img/favicon.ico

footer:
  content: ""